name: Deploy to Shared Hosting

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-dev -o

      - name: Prepare Laravel app
        run: |
          cp .env.production .env
          php artisan key:generate

      - name: Build Laravel app
        run: php artisan optimize

      - name: Deploy to shared hosting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            rsync -avz --exclude='node_modules' --exclude='vendor' ./ ${{ secrets.DEPLOY_DIRECTORY }}
            cd ${{ secrets.DEPLOY_DIRECTORY }}
            bash script.sh
